# Define the reasonable home position that does not clash with anything
joint_state_publisher_gui:
  ros__parameters:
    source_list: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6] 
    zeros:
      joint_1: 0.5  
      joint_2: 1.451
      joint_3: -1.642
      joint_4: 0.0  
      joint_5: 0.0 
      joint_6: 0.0
              
